sudo: required
services:
  - docker

before_install:
  - docker build -t davebulaklak/react-test  -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true davebulaklak/react-test npm test

after_success:
  - docker built -t davebulaklak/multi-client ./client
  - docker built -t davebulaklak/multi-nginx ./nginx
  - docker built -t davebulaklak/multi-server ./server
  - docker built -t davebulaklak/multi-worker ./worker

sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t davebulaklak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davebulaklak/react-test npm test

after_success:
  - docker build -t davebulaklak/multi-client ./client
  - docker build -t davebulaklak/multi-nginx ./nginx
  - docker build -t davebulaklak/multi-server ./server
  - docker build -t davebulaklak/multi-worker ./worker

  # Login to Docker.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker
  - docker push davebulaklak/multi-client
  - docker push davebulaklak/multi-nginx
  - docker push davebulaklak/multi-server
  - docker push davebulaklak/multi-worker

  