sudo: required
services:
  - docker

before_install:
  - docker build -t davebulaklak/react-test  -f Dockerfile.dev ./client

script:
  - docker run -e CI=true davebulaklak/react-test npm test

after_success:
  - docker built -t davebulaklak/multi-client ./client
  - docker built -t davebulaklak/multi-nginx ./nginx
  - docker built -t davebulaklak/multi-server ./server
  - docker built -t davebulaklak/multi-worker ./worker
